/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { gsap } from 'gsap'


export default function FlyingAsteroid({ ...props }) {
  const group = useRef()
  const group2= useRef()
  const group3 = useRef()
  const { nodes, materials } = useGLTF('/threeD/flying-asteroid.glb')

  return (
    <group>
      <group scale={4} rotation={[ 2, 1, 0]} position={[0, 0, 0]} ref={group} {...props} dispose={null}>
        <mesh geometry={nodes.Comet.geometry} material={materials.Stone} position={[0, 0.03, -0.03]} scale={0.01} />
        <mesh geometry={nodes.Tail_radiation.geometry} material={materials['Tail Radiation']} position={[0, 0.02, -0.09]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02} />
        <mesh geometry={nodes.Tail.geometry} material={materials.Stone} position={[-0.01, 0.01, -0.08]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02} />
      </group>
      <group scale={4} rotation={[ 2, 1, 0]} position={[-0.5, 0.8, -1]} ref={group2} {...props} dispose={null}>
        <mesh geometry={nodes.Comet.geometry} material={materials.Stone} position={[0, 0.03, -0.03]} scale={0.01} />
        <mesh geometry={nodes.Tail_radiation.geometry} material={materials['Tail Radiation']} position={[0, 0.02, -0.09]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02} />
        <mesh geometry={nodes.Tail.geometry} material={materials.Stone} position={[-0.01, 0.01, -0.08]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02} />
      </group>
      <group scale={4} rotation={[ 2, 1, 0]} position={[-0.5, -0.4, 0.5]} ref={group3} {...props} dispose={null}>
        <mesh geometry={nodes.Comet.geometry} material={materials.Stone} position={[0, 0.03, -0.03]} scale={0.01} />
        <mesh geometry={nodes.Tail_radiation.geometry} material={materials['Tail Radiation']} position={[0, 0.02, -0.09]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02} />
        <mesh geometry={nodes.Tail.geometry} material={materials.Stone} position={[-0.01, 0.01, -0.08]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02} />
      </group>
    </group>
  )
}

useGLTF.preload('/threeD/flying-asteroid.glb')
