/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF, Float } from '@react-three/drei'


const Monolith = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/threeD/monolith2.glb");
  return (
    <Float
      floatIntensity={0.1}
      rotationIntensity={0.12}
      speed={1}
    >
      <group scale={4} position={[-8, -7, -7]} ref={group} {...props} dispose={null}>
        <mesh
          geometry={nodes.monolith.geometry}
          material={materials.Medusa}
          position={[0.69311343, 0.14294964, 0.20104452]}
          rotation={[-Math.PI / 2.5, Math.PI / 2.6, Math.PI / 8]}
          scale={[0.00038, 0.00152, 0.00335]}
        />
      </group>
    </Float>
  );
}

useGLTF.preload("/threeD/monolith2.glb");

export default Monolith

